# Generated by Django 5.0 on 2024-05-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0002_status_dark_color_status_light_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(
                help_text="Name of the status",
                max_length=60,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="required_level",
            field=models.IntegerField(
                help_text="Minimum required level to achieve the level",
                verbose_name="Required Level",
            ),
        ),
    ]
