# Generated by Django 5.0 on 2024-05-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0004_status_slug_alter_status_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(
                help_text="The display name of the status",
                max_length=50,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="slug",
            field=models.SlugField(
                help_text="The slugyfied version of the status name.",
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
