# Generated by Django 5.0 on 2024-09-28 06:09

import datetime_validators.validators
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("difficulties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the challenge.",
                        max_length=50,
                        verbose_name="Title",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        help_text="Status of the challenge.",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "repeat_type",
                    models.CharField(
                        choices=[
                            ("O", "One time Only"),
                            ("D", "Daily"),
                            ("W", "Weekly"),
                            ("M", "Monthly"),
                        ],
                        default="O",
                        help_text="How often the challenge repeats.",
                        max_length=1,
                        verbose_name="Repeat type",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the challenge is pinned.",
                        verbose_name="Is Pinned",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Due date to complete the challenge.",
                        null=True,
                        validators=[
                            datetime_validators.validators.date_time_is_future_validator
                        ],
                        verbose_name="Due Date",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=1,
                        help_text="Priority order of the challenge.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "difficulty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="difficulties.difficulty",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ChallengeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the step.",
                        max_length=50,
                        verbose_name="Title",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the step is completed.",
                        verbose_name="Completed",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=1,
                        help_text="Priority order of the step.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
