# Generated by Django 5.0 on 2024-05-21 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="description",
        ),
        migrations.AddField(
            model_name="challenge",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_challenges",
                to="challenges.challenge",
            ),
        ),
    ]
