# Generated by Django 5.0 on 2024-05-21 06:10

import datetime_validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0003_alter_challenge_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Due date of the challenge.",
                null=True,
                validators=[
                    datetime_validators.validators.date_time_is_future_validator
                ],
                verbose_name="Due Date",
            ),
        ),
    ]
