# Generated by Django 5.0 on 2024-08-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0006_alter_challengestep_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="repeat_type",
            field=models.CharField(
                choices=[("N", "One-time"), ("D", "Daily"), ("W", "Weekly")],
                default="N",
                help_text="Repeat type of the challenge.",
                max_length=1,
                verbose_name="Repeat type",
            ),
        ),
    ]
