# Generated by Django 5.0 on 2024-08-26 05:04

import datetime_validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0007_challenge_repeat_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Due date to complete the challenge.",
                null=True,
                validators=[
                    datetime_validators.validators.date_time_is_future_validator
                ],
                verbose_name="Due Date",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="repeat_type",
            field=models.CharField(
                choices=[
                    ("O", "One time Only"),
                    ("D", "Daily"),
                    ("W", "Weekly"),
                    ("M", "Monthly"),
                ],
                default="O",
                help_text="How often the challenge repeats.",
                max_length=1,
                verbose_name="Repeat type",
            ),
        ),
    ]
