# Generated by Django 5.0 on 2024-05-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="level",
            field=models.IntegerField(default=1, verbose_name="Level"),
        ),
    ]
