# Generated by Django 5.0 on 2024-05-01 13:52

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usermodel_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="level",
        ),
        migrations.AddField(
            model_name="usermodel",
            name="total_points",
            field=models.IntegerField(
                default=0,
                help_text="Total points (XP) of the user",
                verbose_name="Total Points",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="avatar",
            field=models.ImageField(
                help_text="Avatar (or profile pic) of the user",
                null=True,
                upload_to="uploads/avatars/",
                verbose_name="Avatar",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                help_text="Gender of the user",
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="name",
            field=models.CharField(
                help_text="Name of the user",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="Phone number of the user",
                max_length=128,
                null=True,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
