# Generated by Django 5.0 on 2024-05-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_usermodel_avatar_alter_usermodel_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="total_points",
        ),
        migrations.AddField(
            model_name="usermodel",
            name="total_xp",
            field=models.IntegerField(
                default=0,
                help_text="Total xp points of the user",
                verbose_name="Total XP",
            ),
        ),
    ]
