# Generated by Django 5.0 on 2024-05-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_usermodel_total_points_usermodel_total_xp"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="rank",
            field=models.IntegerField(
                default=0,
                help_text="Global rank of the user",
                verbose_name="Rank",
            ),
        ),
    ]
