# Generated by Django 5.0 on 2024-05-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_usermodel_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="rank",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="Global rank of the user",
                verbose_name="Rank",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="total_xp",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="Total xp points of the user",
                verbose_name="Total XP",
            ),
        ),
    ]
