# Generated by Django 5.0 on 2024-05-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("level_titles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leveltitle",
            name="required_level",
            field=models.PositiveIntegerField(
                help_text="Minimum level requirement to achieve the title",
                unique=True,
                verbose_name="Required Level",
            ),
        ),
    ]
