# Generated by Django 5.0 on 2024-08-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recent_searches", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recentusersearch",
            options={"ordering": ["-searched"]},
        ),
        migrations.RenameField(
            model_name="recentusersearch",
            old_name="searched_at",
            new_name="searched",
        ),
    ]
