# Generated by Django 5.0 on 2024-05-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recent_searches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recentusersearch",
            name="searched_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
