# Generated by Django 5.0 on 2024-05-07 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recent_searches", "0002_recentusersearch_searched_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recentusersearch",
            options={"ordering": ["-searched_at"]},
        ),
        migrations.AlterField(
            model_name="recentusersearch",
            name="searched_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="searchers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recentusersearch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="searches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
