# Generated by Django 5.0 on 2024-04-27 15:54

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Difficulty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The display name of the difficulty level.",
                        max_length=30,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The slugyfied version of the difficulty name.",
                        max_length=30,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        help_text="The display color of the difficulty level.",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Color",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        help_text="Number of points associated with this difficulty level.",
                        verbose_name="Points",
                    ),
                ),
            ],
        ),
    ]
