# Generated by Django 5.0 on 2024-05-08 04:10

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Difficulty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The display name of the difficulty level.",
                        max_length=30,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The slugyfied version of the difficulty name.",
                        max_length=30,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "light_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        help_text="The display color for ligth theme.",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Ligth Color",
                    ),
                ),
                (
                    "dark_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        help_text="The display color for dark theme.",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Dark Color",
                    ),
                ),
                (
                    "xp_value",
                    models.PositiveIntegerField(
                        help_text="Number of xp value associated with this difficulty level.",
                        verbose_name="XP Value",
                    ),
                ),
            ],
            options={
                "ordering": ("xp_value",),
            },
        ),
    ]
