# Generated by Django 5.0 on 2024-04-27 08:51

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("difficulties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="difficulty",
            name="slug",
            field=models.SlugField(
                default="easy",
                help_text="Required. The slugyfied version of the difficulty name.",
                max_length=30,
                unique=True,
                verbose_name="Slug",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="difficulty",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                help_text="The display color of the difficulty level.",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="difficulty",
            name="name",
            field=models.CharField(
                help_text="Required. The display name of the difficulty level.",
                max_length=30,
                verbose_name="Name",
            ),
        ),
    ]
