# Generated by Django 5.0 on 2024-06-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("difficulties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="difficulty",
            name="xp_value",
            field=models.PositiveIntegerField(
                help_text="Number of xp value associated with this difficulty level.",
                max_length=1000,
                verbose_name="XP Value",
            ),
        ),
    ]
