# Generated by Django 5.0 on 2024-05-01 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("difficulties", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="difficulty",
            options={"ordering": ("points",)},
        ),
    ]
