# Generated by Django 5.0 on 2024-04-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "difficulties",
            "0002_difficulty_slug_alter_difficulty_color_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="difficulty",
            name="name",
            field=models.CharField(
                help_text="The display name of the difficulty level.",
                max_length=30,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="difficulty",
            name="points",
            field=models.PositiveIntegerField(
                help_text="Number of points associated with this difficulty level.",
                verbose_name="Points",
            ),
        ),
        migrations.AlterField(
            model_name="difficulty",
            name="slug",
            field=models.SlugField(
                help_text="The slugyfied version of the difficulty name.",
                max_length=30,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
