# Generated by Django 5.0 on 2024-06-03 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("difficulties", "0003_alter_difficulty_xp_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="difficulty",
            name="xp_value",
            field=models.PositiveIntegerField(
                help_text="Number of xp value associated with this difficulty level.",
                validators=[django.core.validators.MaxValueValidator(1000)],
                verbose_name="XP Value",
            ),
        ),
    ]
