# Generated by Django 5.0 on 2024-05-08 04:10

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LevelTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the level",
                        max_length=50,
                        verbose_name="Title",
                    ),
                ),
                (
                    "required_level",
                    models.PositiveIntegerField(
                        help_text="Minimum level requirement to achieve the title",
                        unique=True,
                        verbose_name="Required Level",
                    ),
                ),
                (
                    "light_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        help_text="The display color for ligth theme.",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Ligth Color",
                    ),
                ),
                (
                    "dark_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        help_text="The display color for dark theme.",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Dark Color",
                    ),
                ),
            ],
        ),
    ]
