# Generated by Django 5.0 on 2024-06-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("level_titles", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="level_titles",
            field=models.ManyToManyField(to="level_titles.leveltitle"),
        ),
    ]
