# Generated by Django 5.0 on 2024-07-07 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("level_titles", "0002_alter_leveltitle_options"),
        ("users", "0003_remove_usermodel_level_titles_usermodel_level_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="level_title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="users",
                to="level_titles.leveltitle",
            ),
        ),
    ]
