# Generated by Django 5.0 on 2024-04-27 12:24

import api.challenges.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "difficulties",
            "0003_alter_difficulty_name_alter_difficulty_points_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the challenge.",
                        max_length=50,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the challenge.",
                        max_length=200,
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_pinned",
                    models.CharField(
                        help_text="Whether the challenge is pinned.",
                        max_length=30,
                        verbose_name="Is Pinned",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        help_text="Due date of the challenge.",
                        null=True,
                        validators=[
                            api.challenges.models.date_time_is_future_validator
                        ],
                        verbose_name="Due Date",
                    ),
                ),
                (
                    "difficulty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="difficulties.difficulty",
                    ),
                ),
            ],
        ),
    ]
