# Generated by Django 5.0 on 2024-05-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="order",
            field=models.IntegerField(
                default=1,
                help_text="Priority order of the challenge.",
                verbose_name="Order",
            ),
        ),
    ]
