# Generated by Django 5.0 on 2024-05-21 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0002_remove_challenge_description_challenge_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_challenges",
                to="challenges.challenge",
            ),
        ),
    ]
