# Generated by Django 5.0 on 2024-05-22 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0004_alter_challenge_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="parent",
        ),
        migrations.CreateModel(
            name="ChallengeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the step.",
                        max_length=50,
                        verbose_name="Title",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the step is completed.",
                        verbose_name="Completed",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=1,
                        help_text="Priority order of the step.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="challenges.challenge",
                    ),
                ),
            ],
        ),
    ]
